services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wPrP80
      
  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    Host: mysql
    User: admin_user
    Password: P#q3dJ/4
    Database: wordpress
  tags:
    - dev2ops
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
  tags:
    dev2ops