services:
  - db
  - adminer

db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: wPrP80
    MYSQL_USER: admin_user
    MYSQL_PASSWORD: P#q3dJ/4
      
adminer:
  image: adminer
  restart: always
  ports:
    - 80:8080
tags:
  - dev2ops