services: mysql:5.7
variables:
  MYSQL_ROOT_PASSWORD: wPrP80
  MYSQL_DATABASE: wordpress
  MYSQL_USER: admin_user
  MYSQL_PASSWORD: P#q3dJ/4

deploy:
  stage: deploy
  script:
    - cat ansible.txt
  tags:
    - dev2ops